set_property PACKAGE_PIN L19 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN M19 [get_ports enable]

set_property IOSTANDARD LVCMOS33 [get_ports running]
set_property PACKAGE_PIN L14 [get_ports running]

set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
set_property PACKAGE_PIN U13 [get_ports R]
set_property PACKAGE_PIN V13 [get_ports G]
set_property PACKAGE_PIN V15 [get_ports B]
set_property PACKAGE_PIN T15 [get_ports HSYNC]
set_property PACKAGE_PIN R16 [get_ports VSYNC]

set_property IOSTANDARD LVCMOS33 [get_ports {controllers_keuze_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_keuze_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_keuze_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_keuze_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports controller_inductief_in]
set_property IOSTANDARD LVCMOS33 [get_ports controller_ultrasoon_in]
set_property IOSTANDARD LVCMOS33 [get_ports controller_ultrasoon_trigger]
set_property IOSTANDARD LVCMOS33 [get_ports controller_draadloos_verbonden]
set_property IOSTANDARD LVCMOS33 [get_ports controller_draadloos_omhoog]
set_property IOSTANDARD LVCMOS33 [get_ports controller_draadloos_omlaag]

set_property PACKAGE_PIN Y18 [get_ports {controllers_keuze_1[0]}]
set_property PACKAGE_PIN U18 [get_ports {controllers_keuze_1[1]}]
set_property PACKAGE_PIN Y19 [get_ports {controllers_keuze_2[0]}]
set_property PACKAGE_PIN U19 [get_ports {controllers_keuze_2[1]}]
set_property PACKAGE_PIN W14 [get_ports controller_inductief_in]
set_property PACKAGE_PIN Y16 [get_ports controller_ultrasoon_in]
set_property PACKAGE_PIN W18 [get_ports controller_ultrasoon_trigger]
set_property PACKAGE_PIN T11 [get_ports controller_draadloos_verbonden]
set_property PACKAGE_PIN T10 [get_ports controller_draadloos_omhoog]
set_property PACKAGE_PIN W13 [get_ports controller_draadloos_omlaag]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN R14 [get_ports {leds[0]}]
set_property PACKAGE_PIN P14 [get_ports {leds[1]}]