set_property PACKAGE_PIN L19 [get_ports reset]
set_property PACKAGE_PIN L20 [get_ports reset_hw]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset_hw]

set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN M19 [get_ports enable]

set_property IOSTANDARD LVCMOS33 [get_ports status_running]
set_property PACKAGE_PIN L14 [get_ports status_running]

set_property IOSTANDARD LVCMOS33 [get_ports display_R]
set_property IOSTANDARD LVCMOS33 [get_ports display_G]
set_property IOSTANDARD LVCMOS33 [get_ports display_B]
set_property IOSTANDARD LVCMOS33 [get_ports display_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports display_VSYNC]
set_property PACKAGE_PIN U13 [get_ports display_R]
set_property PACKAGE_PIN V13 [get_ports display_G]
set_property PACKAGE_PIN V15 [get_ports display_B]
set_property PACKAGE_PIN T15 [get_ports display_HSYNC]
set_property PACKAGE_PIN R16 [get_ports display_VSYNC]

set_property IOSTANDARD LVCMOS33 [get_ports {controllers_choice_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_choice_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_choice_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controllers_choice_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports controller_inductief_in]
set_property IOSTANDARD LVCMOS33 [get_ports controller_ultrasoon_in]
set_property IOSTANDARD LVCMOS33 [get_ports controller_ultrasoon_trigger]
set_property IOSTANDARD LVCMOS33 [get_ports controller_draadloos_in]

set_property PACKAGE_PIN Y18 [get_ports {controllers_choice_1[0]}]
set_property PACKAGE_PIN U18 [get_ports {controllers_choice_1[1]}]
set_property PACKAGE_PIN Y19 [get_ports {controllers_choice_2[0]}]
set_property PACKAGE_PIN U19 [get_ports {controllers_choice_2[1]}]
set_property PACKAGE_PIN W14 [get_ports controller_inductief_in]
set_property PACKAGE_PIN Y16 [get_ports controller_ultrasoon_in]
set_property PACKAGE_PIN W18 [get_ports controller_ultrasoon_trigger]
set_property PACKAGE_PIN T11 [get_ports controller_draadloos_in]