# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_interconn_0_0/design_1_controller_interconn_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controller_interconn_0_0 || ORIG_REF_NAME==design_1_controller_interconn_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_inductief_0_0/design_1_controller_inductief_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controller_inductief_0_0 || ORIG_REF_NAME==design_1_controller_inductief_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_draadloos_0_0/design_1_controller_draadloos_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controller_draadloos_0_0 || ORIG_REF_NAME==design_1_controller_draadloos_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_divider_0_0/design_1_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_divider_0_0 || ORIG_REF_NAME==design_1_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_ultrasoon_0_0/design_1_controller_ultrasoon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controller_ultrasoon_0_0 || ORIG_REF_NAME==design_1_controller_ultrasoon_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_divider_0_1/design_1_clk_divider_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_divider_0_1 || ORIG_REF_NAME==design_1_clk_divider_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_beeld_generator_0_0/design_1_beeld_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_beeld_generator_0_0 || ORIG_REF_NAME==design_1_beeld_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_peddels_hoogte_0/design_1_peddels_hoogte_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_peddels_hoogte_0 || ORIG_REF_NAME==design_1_peddels_hoogte_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_peddels_hoogte_1/design_1_peddels_hoogte_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_peddels_hoogte_1 || ORIG_REF_NAME==design_1_peddels_hoogte_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_peddels_hoogte_2/design_1_peddels_hoogte_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_peddels_hoogte_2 || ORIG_REF_NAME==design_1_peddels_hoogte_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_peddels_hoogte_3/design_1_peddels_hoogte_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_peddels_hoogte_3 || ORIG_REF_NAME==design_1_peddels_hoogte_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_peddels_hoogte_4/design_1_peddels_hoogte_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_peddels_hoogte_4 || ORIG_REF_NAME==design_1_peddels_hoogte_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_scherm_hoogte_0/design_1_scherm_hoogte_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_scherm_hoogte_0 || ORIG_REF_NAME==design_1_scherm_hoogte_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lijn_tekenen_0_0/design_1_lijn_tekenen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lijn_tekenen_0_0 || ORIG_REF_NAME==design_1_lijn_tekenen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tekenen_object_0_0/design_1_tekenen_object_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tekenen_object_0_0 || ORIG_REF_NAME==design_1_tekenen_object_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Coor_PixelR_0_0/design_1_Coor_PixelR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Coor_PixelR_0_0 || ORIG_REF_NAME==design_1_Coor_PixelR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Coor_PixelL_0_0/design_1_Coor_PixelL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Coor_PixelL_0_0 || ORIG_REF_NAME==design_1_Coor_PixelL_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_score_tekenen_0_0/design_1_score_tekenen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_score_tekenen_0_0 || ORIG_REF_NAME==design_1_score_tekenen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aanraking_herkennen_0_0/design_1_aanraking_herkennen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_aanraking_herkennen_0_0 || ORIG_REF_NAME==design_1_aanraking_herkennen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_score_counter_0_0/design_1_score_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_score_counter_0_0 || ORIG_REF_NAME==design_1_score_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_positie_balletje_0_0/design_1_positie_balletje_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_positie_balletje_0_0 || ORIG_REF_NAME==design_1_positie_balletje_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_frequency_to_number_0_0/design_1_frequency_to_number_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_frequency_to_number_0_0 || ORIG_REF_NAME==design_1_frequency_to_number_0_0} -quiet] -quiet

# XDC: d:/Vivado/mo6-digitaal-totaal/mo6-digitaal-pong.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado/mo6-digitaal-totaal/mo6-digitaal-pong.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado/mo6-digitaal-totaal/mo6-digitaal-pong.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: d:/Vivado/mo6-digitaal-totaal/mo6-digitaal-pong.gen/sources_1/bd/design_1/design_1_ooc.xdc
